apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "conveyor.fullname" . }}
  labels: {{- include "conveyor.labels" . | nindent 4 }}
data:
  PHX_HOST: {{ .Values.hosts.web | quote }}
  PORT: "4000"
  GRPC_PORT: "1985"
  {{- if .Values.cluster.enabled }}
  CLUSTER_STRATEGY: k8s
  CLUSTER_K8S_SERVICE: {{ include "conveyor.fullname" . }}-headless
  CLUSTER_NODE_BASENAME: {{ .Values.cluster.nodeBasename | quote }}
  {{- else }}
  CLUSTER_STRATEGY: none
  {{- end }}
  {{- if .Values.persistence.enabled }}
  BLOB_DIR: /var/lib/conveyor/blobs
  {{- end }}
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
