{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "conveyor.fullname" . }}
  labels: {{- include "conveyor.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "conveyor.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
